### ISSUE TITLE
Conflict with other plugins.

### ISSUE THREAD

**Issue by DanieL800-xe** [cengiz-pz/godot-android-deeplink-plugin#4]
The Deeplink plugin is likely conflicting with the Share and AdMob plugins. In my android app, I use all three of your plugins, and if I close advertisement or close sharing, the app doesn't continue as expected but instead triggers the deeplink signal. I'm not a professional programmer, but I have a feeling that the issue isn't on my end. Can you please verify this?

**Comment by cengiz-pz** [comment]
Hi @DanieL800-xe, I use [all five plugins](https://github.com/cengiz-pz/godot-android-deeplink-plugin?tab=readme-ov-file#-all-plugins) & haven't had any conflicts.  Could you please provide more information on the issue that you're experiencing, preferrably a minimal project where the issue is reproducible?

**Comment by DanieL800-xe** [comment]
I noticed that when I switch to another app and then reopen it, the same thing happens... it's as if the deeplink signal is triggered. However, this only occurs if the deeplink has already been activated in the app. If I open the app for the first time without a deeplink, everything works as it should... but once I open the deeplink, there are many instances where it triggers again. Maybe the issue really is on my end. I'll check it thoroughly.

**Comment by cengiz-pz** [comment]
@DanieL800-xe, once you're done processing the deeplink and don't need it anymore, call `clear_data()` to remove it from plugin cache.

**Comment by DanieL800-xe** [comment]
It works. Thank you very much !
