### ISSUE TITLE
Thank you :) you're doing a great service to the Godot community!

### ISSUE THREAD

**Issue by SlakkedisStudio** [cengiz-pz/godot-android-deeplink-plugin#8]
Just wanted to say thank you for your contribution and for providing these plugins to the community.

I have only recently come across your git profile and we started using the in-app review plugin. 
Configuration was super simple and easy, unlike many of the other plugins out there.

I like the fact that you have created your own node that is self-contained. 

Lastly, I wanted to say that we are running a github action pipeline for our Android deployments and the fact that this just worked out of the box and we didn't have to configure anything in manifest is just amazing!

Oh, and it was great to see that the binaries and archives were readily available for the exact Godot version I am using! 

Thanks again!

If you don't have a website, YouTube tutorials, I suggest doing these as you'll get a lot of traction!

**Comment by cengiz-pz** [comment]
Thank you for the kind words, @SlakkedisStudio.  I'm glad that you find the plugins useful.  Usually, I am only supporting the latest Godot version - the backport of the Deeplink plugin for Godot 3.5 was a special request.

Thank you for your suggestions.  Maybe sometime in the future if I find some time.
